version: "3.8"

services:
    api:
        build: ./api
        restart: unless-stopped
        ports: 
            - 8080:8080
        environment:
            - MONGO_PORT=27017
            - MONGO_NAME=imageDB
            - STATIC_PATH=static/images/
        volumes:
            - ./api:/api
    db:
        image: mongo
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - ./imagedb:/data/db